using System.Text.Json.Serialization;
using sevDeskNET.Internal.ApiModels;

namespace sevDeskNET.Internal;

[JsonSerializable(typeof(SevDeskApiResponse<ApiContact>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiContact>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiInvoice>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiInvoice>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiInvoicePos>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiInvoicePos>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiOrder>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiOrder>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiOrderPos>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiOrderPos>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiVoucher>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiVoucher>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiVoucherPos>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiVoucherPos>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCreditNote>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCreditNote>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCreditNotePos>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCreditNotePos>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiPart>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiPart>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCheckAccount>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCheckAccount>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCheckAccountTransaction>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCheckAccountTransaction>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCommunicationWay>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCommunicationWay>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiContactAddress>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiContactAddress>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiTag>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiTag>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCategory>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCategory>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiUnity>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiUnity>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiTaxRule>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiTaxRule>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiCurrencyExchangeRate>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiCurrencyExchangeRate>))]
[JsonSerializable(typeof(SevDeskApiResponse<ApiDocument>))]
[JsonSerializable(typeof(SevDeskApiListResponse<ApiDocument>))]
[JsonSerializable(typeof(ApiSaveInvoiceRequest))]
[JsonSerializable(typeof(ApiSaveOrderRequest))]
[JsonSerializable(typeof(ApiSaveVoucherRequest))]
[JsonSerializable(typeof(ApiSaveCreditNoteRequest))]
[JsonSerializable(typeof(ApiChangeStatusRequest))]
[JsonSerializable(typeof(ApiSendEmailRequest))]
[JsonSerializable(typeof(ApiBookAmountRequest))]
[JsonSerializable(typeof(ApiGetNextNumberResponse))]
[JsonSerializable(typeof(ApiBalanceResponse))]
[JsonSerializable(typeof(ApiContact))]
[JsonSerializable(typeof(ApiInvoice))]
[JsonSerializable(typeof(ApiInvoicePos))]
[JsonSerializable(typeof(ApiOrderPos))]
[JsonSerializable(typeof(ApiVoucherPos))]
[JsonSerializable(typeof(ApiCreditNotePos))]
[JsonSerializable(typeof(ApiOrder))]
[JsonSerializable(typeof(ApiVoucher))]
[JsonSerializable(typeof(ApiCreditNote))]
[JsonSerializable(typeof(ApiPart))]
[JsonSerializable(typeof(ApiCheckAccount))]
[JsonSerializable(typeof(ApiCheckAccountTransaction))]
[JsonSerializable(typeof(ApiCommunicationWay))]
[JsonSerializable(typeof(ApiContactAddress))]
[JsonSerializable(typeof(ApiTag))]
[JsonSerializable(typeof(ApiCategory))]
[JsonSerializable(typeof(ApiUnity))]
[JsonSerializable(typeof(ApiTaxRule))]
[JsonSerializable(typeof(ApiCurrencyExchangeRate))]
[JsonSerializable(typeof(ApiDocument))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
internal partial class SevDeskJsonContext : JsonSerializerContext;
